version: '3'
services:
  food-server:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=harkirat
      - MONGO_PASSWORD=harkirat
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=harkirat
      - MONGO_INITDB_ROOT_PASSWORD=harkirat