version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  food-server:
    build: .
    image: harkiratsm/food-server
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=harkirat
      - MONGO_INITDB_ROOT_PASSWORD=harkirat
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: